# Generated by Django 4.1.13 on 2024-01-31 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flippyapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AlterField(
            model_name='orderwithaddress',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='orderwithaddress',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='flippyapp.orderitem'),
        ),
        migrations.AddField(
            model_name='orderwithaddress',
            name='order_items',
            field=models.ManyToManyField(to='flippyapp.orderitem'),
        ),
    ]
